version: '3.0'
services:
    database:
        image: 'mongo' 
        container_name: 'mongo-database'
        environment: 
            - MONGO_INITDB_DATABASE=database
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes: 
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongo-volume:/data/db
        ports: 
            - '27017-27019:27017-27019'
    api:
        build: 
            context: api
        volumes:  
            - ./api:/app
        ports: 
            - '8000:8000'
        depends_on:
            database:
                condition: service_healthy

