version: '3'

services:
  
  #web:
  #  build:
  #    context: api
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - "./api:/app"
  #  depends_on: 
  #    - database
  


  database:
    image: "mongo"
    
    environment: 
      - MONGO_INTDB_DATABASE="database"
      - MONGO_INTDB_ROOT_USERNAME="admin"
      - MONGO_INTDB_ROOT_PASSWORD="admin"
    volumes: 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports: 
      - '27017:27017' 
    
      
  #test:
  #  build:
  #    context: api
  #    dockerfile: ./api/Dockerfile.test
  #  ports:
  #    - "8001:8001"
  #  volumes:
  #    - $PWD:/home/memez-michalek/Desktop/projects/webshop/
  #  depends_on: 
  #    - database
  #  networks:
  #    - integration-test
  
